[tool.poetry]
authors = ["FL03 <j03mccain@icloud.com>"]
description = ""
license = "Apache-2.0"
name = "synapse"
packages = [{include = "synapse", from = "src"}]
readme = "README.md"
version = "0.1.0"

[tool.poetry.dependencies]
bcrypt = "^4.0.0"
cryptography = "^39.0.0"
fastapi = {extras = ["all"], version = "^0.89.0"}
openai = "^0.25.0"
passlib = "^1.7.4"
python = ">=3.8,<3.12"
python-dotenv = "^0.21.0"
python-jose = "^3.3.0"
python-telegram-bot = "^20.0"
strawberry-graphql = {extras = ["fastapi"], version = "^0.151.2"}
stripe = "^5.0.0"
tortoise-orm = { extras = ["asyncpg"], version = "^0.19.2" }

[tool.poetry.dev-dependencies]
black = "22.12.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
